/**
 * Act two: the proof. One real product answer on Faheem's own paper, framed
 * in the arch, with the examiner's verification told plainly. Markdown +
 * NotebookViewer are the product's own renderers on the product's own
 * output — nothing staged.
 */
import { motion } from "motion/react";
import { Sparkles, BookMarked, CheckCircle2, BookOpen } from "lucide-react";
import { parseTeachingSections } from "../utils";
import { Markdown } from "../Markdown";
import { NotebookViewer } from "../NotebookViewer";
import { REAL_QUESTION, REAL_ANSWER } from "./realAnswer";
import { useCalm, fadeUp, sheetRise } from "./reveals";

const parsed = parseTeachingSections(REAL_ANSWER);

const CHIPS = [
  { icon: Sparkles, label: "Teach me again" },
  { icon: CheckCircle2, label: "Verify" },
  { icon: BookMarked, label: "Save lines" },
  { icon: BookOpen, label: "Go deeper" },
];

export default function AnswerAct() {
  const calm = useCalm();

  return (
    <section id="watch" className="landing-cv landing-cv-answer bg-page px-5 py-20 text-ink md:px-8 md:py-28" aria-label="A real answer from Faheem">
      <div className="mx-auto max-w-6xl">
        <div className="mx-auto max-w-3xl text-center">
          <motion.p {...fadeUp(calm)} className="fhm-eyebrow fhm-eyebrow-ink">
            A real answer, start to finish
          </motion.p>
          <motion.h2
            {...fadeUp(calm, calm ? 0 : 0.08)}
            className="kod-display landing-balance mt-4 text-[clamp(1.9rem,5vw,3rem)] leading-[1.1] text-ink"
          >
            Watch Faheem teach, then check his own work.
          </motion.h2>
          <motion.p {...fadeUp(calm, calm ? 0 : 0.16)} className="landing-pretty mx-auto mt-5 max-w-2xl text-[15px] leading-relaxed text-ink-dim md:text-base">
            Every answer is written for your level, then read again in full by a
            second examiner pass that verifies the facts and the calculations
            before it settles on your screen. What you keep is the checked
            final, never the first draft. This one is shown exactly as the
            product renders it.
          </motion.p>
        </div>

        {/* The question, asked the way a student actually asks */}
        <motion.div {...sheetRise(calm)} className="mx-auto mt-12 flex max-w-4xl flex-col items-end">
          <p className="mb-2 text-xs font-semibold uppercase tracking-[0.14em] text-ink-dim">The student</p>
          <div className="max-w-xl rounded-3xl rounded-br-md border border-gold-line bg-surface p-5 text-sm leading-relaxed text-ink shadow-sm md:text-base">
            {REAL_QUESTION}
          </div>
        </motion.div>

        {/* The answer: the product's own paper inside the arch frame */}
        <motion.div {...sheetRise(calm, calm ? 0 : 0.1)} className="mx-auto mt-6 max-w-4xl">
          <div className="flex flex-wrap items-center gap-2 px-1 pb-3">
            <span className="kod-pill bg-ink text-page">Faheem</span>
            <span className="kod-pill border border-ink-line bg-surface text-ink">High-school profile</span>
            <span className="kod-pill ml-auto hidden items-center gap-1.5 bg-teal-pale text-teal-deep sm:inline-flex">
              <CheckCircle2 size={12} /> verified answer
            </span>
          </div>
          <div className="lit-sheet bg-editorial-ivory p-4 text-editorial-charcoal sm:p-6 md:p-8">
            <div className="text-sm leading-relaxed md:text-base">
              {parsed.preamble && (
                <div className="mb-3">
                  <Markdown>{parsed.preamble}</Markdown>
                </div>
              )}
              <NotebookViewer sections={parsed.sections} />
              {/* The real action row under every answer, kept in step with the app. */}
              <div aria-hidden="true" className="pointer-events-none mt-3 flex flex-wrap items-center gap-1.5 border-t border-editorial-line-light pt-2.5 select-none">
                {CHIPS.map((c) => (
                  <span key={c.label} className={`flex items-center gap-1.5 whitespace-nowrap rounded-full border border-editorial-line-light bg-editorial-stone px-3 py-1 text-xs text-editorial-sage ${c.label === "Go deeper" ? "sm:ml-auto" : ""}`}>
                    <c.icon size={12} /> {c.label}
                  </span>
                ))}
              </div>
            </div>
          </div>
          <p className="landing-pretty mt-4 text-center text-[13px] leading-relaxed text-ink-dim">
            Generated by Faheem for a high-school profile. The flowchart, the
            quick check, the shopping-cart analogy: all of it came from the
            tutor, through the product&rsquo;s own renderer.
          </p>
        </motion.div>
      </div>
    </section>
  );
}
